### PR TITLE
Update documentations

### PR DESCRIPTION
**Pull request by fisuda**
This PR updates documentations.

### CODE REVIEW

**Comment by fisuda** [comment]
I have sent this PR to master branch, not NGSI-v2. Sorry.

**Review by jason-fox — APPROVED** [review]
I now see you are fixing the Spanish 🇪🇸  🇯🇵 

LGTM.

**Comment by fisuda** [comment]
I only have updated TOC in the Spanish version  by copy & paste. 😄

**Comment by jason-fox** [comment]
That is **still** better than my spanish.

**Comment by jason-fox** [comment]
... or my Japanese.

**Pull request merged**
